//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public int goals { get; set; }
        public int owngoals { get; set; }
        public int points { get; set; }
        public int wins { get; set; }
        public int loses { get; set; }
        public int draws { get; set; }
        public int totalGames { get; set; }
    
        public virtual User User { get; set; }
        public virtual Team Team { get; set; }
        public virtual GroupCard GroupCard { get; set; }
    }
}
